import React from 'react';
import { View } from 'react-native';

const createMockIcon = (displayName) => {
  const MockIcon = React.forwardRef((props, ref) => 
    React.createElement(View, { 
      ref,
      testID: `icon-${displayName}`,
      ...props 
    })
  );
  MockIcon.displayName = displayName;
  return MockIcon;
};

const icons = {
  LogOut: createMockIcon('LogOut'),
  ShieldCheck: createMockIcon('ShieldCheck'),
  Edit: createMockIcon('Edit'),
  Edit3: createMockIcon('Edit3'),
  Link: createMockIcon('Link'),
  Space: createMockIcon('Space'),
  Trash: createMockIcon('Trash'),
  Trash2: createMockIcon('Trash2'),
  ArrowLeft: createMockIcon('ArrowLeft'),
  Camera: createMockIcon('Camera'),
  Save: createMockIcon('Save'),
  Eye: createMockIcon('Eye'),
  EyeIcon: createMockIcon('EyeIcon'),
  EyeOff: createMockIcon('EyeOff'),
  EyeOffIcon: createMockIcon('EyeOffIcon'),
  Plus: createMockIcon('Plus'),
  X: createMockIcon('X'),
  Settings: createMockIcon('Settings'),
  Home: createMockIcon('Home'),
  Search: createMockIcon('Search'),
  Menu: createMockIcon('Menu'),
  Bell: createMockIcon('Bell'),
  User: createMockIcon('User'),
  UserPlus: createMockIcon('UserPlus'),
  LogIn: createMockIcon('LogIn'),
  AlertCircle: createMockIcon('AlertCircle'),
  Check: createMockIcon('Check'),
  CheckCircle: createMockIcon('CheckCircle'),
  ChevronRight: createMockIcon('ChevronRight'),
  ChevronLeft: createMockIcon('ChevronLeft'),
  ChevronDown: createMockIcon('ChevronDown'),
  ChevronUp: createMockIcon('ChevronUp'),
  ArrowRight: createMockIcon('ArrowRight'),
  Download: createMockIcon('Download'),
  Upload: createMockIcon('Upload'),
  Loader: createMockIcon('Loader'),
  MoreVertical: createMockIcon('MoreVertical'),
  Server: createMockIcon('Server'),
  GitBranch: createMockIcon('GitBranch'),
  Terminal: createMockIcon('Terminal'),
  Info: createMockIcon('Info'),
  AlertTriangle: createMockIcon('AlertTriangle'),
  XCircle: createMockIcon('XCircle'),
  Zap: createMockIcon('Zap'),
  Target: createMockIcon('Target'),
  Shield: createMockIcon('Shield'),
  Code: createMockIcon('Code'),
  Github: createMockIcon('Github'),
  Globe: createMockIcon('Globe'),
  Users: createMockIcon('Users'),
  Lightbulb: createMockIcon('Lightbulb'),
  Rocket: createMockIcon('Rocket'),
  Activity: createMockIcon('Activity'),
  TrendingUp: createMockIcon('TrendingUp'),
  MessageCircle: createMockIcon('MessageCircle'),
  Music: createMockIcon('Music'),
  Mail: createMockIcon('Mail'),
  FileSpreadsheet: createMockIcon('FileSpreadsheet'),
  KeyRound: createMockIcon('KeyRound'),
  LockKeyhole: createMockIcon('LockKeyhole'),
  Filter: createMockIcon('Filter'),
  HelpCircle: createMockIcon('HelpCircle'),
  Moon: createMockIcon('Moon'),
  Sun: createMockIcon('Sun'),
  Circle: createMockIcon('Circle'),
  Clock: createMockIcon('Clock'),
  Phone: createMockIcon('Phone'),
  Send: createMockIcon('Send'),
  Unlink: createMockIcon('Unlink'),
  Play: createMockIcon('Play'),
  Power: createMockIcon('Power'),
  PowerOff: createMockIcon('PowerOff'),
  RefreshCw: createMockIcon('RefreshCw'),
  Webhook: createMockIcon('Webhook'),
  ToggleRight: createMockIcon('ToggleRight'),
  ToggleLeft: createMockIcon('ToggleLeft'),
};

module.exports = icons;
